/* =====================================================================
   plants.js — 出題データ
   ---------------------------------------------------------------------
   file : Wikimedia Commons のファイル名。写真は
          https://commons.wikimedia.org/wiki/Special:FilePath/<file>?width=900
          から読み込み、クレジットは File ページへリンクします。
   photo: ローカル画像を使いたい場合のパス（例 'images/monstera.jpg'）。
          指定するとこちらが優先されます。
   写真が読み込めなかったときは art.js のイラストに自動でフォールバック。
   near : 「間違えやすい植物」の id。選択肢を作るときに優先されます。
   ===================================================================== */

const PLANTS = [
  {
    id: 'monstera',
    name: 'モンステラ',
    latin: 'Monstera deliciosa',
    file: 'Swiss_Cheese_Plant_(Monstera_deliciosa)_(2858303740).jpg',
    photo: null,
    tint: '#e6f1e2',
    fact: '成長すると葉に深い切れ込みと穴があく「葉の窓」が特徴。原産は熱帯アメリカで、耐陰性が高く初心者向けの定番です。',
    near: ['pothos', 'umbellata', 'schefflera', 'calathea', 'platycerium'],
  },
  {
    id: 'sansevieria',
    name: 'サンスベリア',
    latin: 'Dracaena trifasciata',
    file: 'Sansevieria_trifasciata_Plant_3264px.jpg',
    photo: null,
    tint: '#eaefe0',
    fact: '「虎の尾」とも呼ばれる多肉質の葉。乾燥に非常に強く、水のやりすぎが最大の枯らす原因です。',
    near: ['aloe', 'dracaena', 'zamioculcas', 'strelitzia', 'chlorophytum'],
  },
  {
    id: 'pothos',
    name: 'ポトス',
    latin: 'Epipremnum aureum',
    file: 'Epipremnum_aureum_31082012.jpg',
    photo: null,
    tint: '#eaf3e4',
    fact: 'ハート形の葉に黄色い斑が入るつる性植物。水挿しでも簡単に増やせる、もっとも育てやすい観葉植物のひとつ。',
    near: ['monstera', 'chlorophytum', 'umbellata', 'calathea', 'everfresh'],
  },
  {
    id: 'pachira',
    name: 'パキラ',
    latin: 'Pachira aquatica',
    file: 'Braided_Money_Tree_Plant_(Pachira_aquatica)_1.jpg',
    photo: null,
    tint: '#e9f0e6',
    fact: '「発財樹（money tree）」の別名を持つ縁起物。編み込まれた幹と、手のひら状に広がる5〜7枚の小葉が目印。',
    near: ['schefflera', 'umbellata', 'everfresh', 'gajumaru', 'ficusElastica'],
  },
  {
    id: 'gajumaru',
    name: 'ガジュマル',
    latin: 'Ficus microcarpa',
    file: 'Ficus_microcarpa_bonsai_Kiev.jpg',
    photo: null,
    tint: '#edf1e2',
    fact: '沖縄では精霊「キジムナー」が宿る木とされる。ぷっくり太った幹（気根）と小さな丸い葉が特徴です。',
    near: ['pachira', 'ficusElastica', 'umbellata', 'everfresh', 'schefflera'],
  },
  {
    id: 'umbellata',
    name: 'フィカス・ウンベラータ',
    latin: 'Ficus umbellata',
    file: 'Ficus_umbellata_(jetalone).jpg',
    photo: null,
    tint: '#eaf2e5',
    fact: '大きなハート形の葉と、くねりのある細い幹が人気。同じフィカス属のゴムの木より葉が薄く、明るい緑色です。',
    near: ['ficusElastica', 'monstera', 'pothos', 'gajumaru', 'pachira'],
  },
  {
    id: 'ficusElastica',
    name: 'ゴムの木（フィカス・エラスティカ）',
    latin: 'Ficus elastica',
    file: 'Ficus_elastica_557.jpg',
    photo: null,
    tint: '#eef0e6',
    fact: '厚く光沢のある楕円形の葉。新芽が赤い鞘に包まれて出てくるのが特徴で、かつて天然ゴムの原料にされました。',
    near: ['umbellata', 'gajumaru', 'calathea', 'schefflera', 'dracaena'],
  },
  {
    id: 'aloe',
    name: 'アロエ・ベラ',
    latin: 'Aloe vera',
    file: 'Aloe_Vera_plant.jpg',
    photo: null,
    tint: '#f0f1e0',
    fact: '縁にトゲのある多肉質のロゼット。葉の中のゼリー状の葉肉が、古くから民間薬・食用に使われてきました。',
    near: ['sansevieria', 'echinocactus', 'zamioculcas', 'strelitzia', 'chlorophytum'],
  },
  {
    id: 'chlorophytum',
    name: 'オリヅルラン',
    latin: 'Chlorophytum comosum',
    file: 'Spider_Plant_(Chlorophytum_comosum).jpg',
    photo: null,
    tint: '#ebf2e2',
    fact: '細長い斑入りの葉が弧を描き、ランナー（走出枝）の先に子株を付けます。その姿を折り鶴に見立てた名前。',
    near: ['dracaena', 'pothos', 'sansevieria', 'chamaedorea', 'calathea'],
  },
  {
    id: 'schefflera',
    name: 'シェフレラ（カポック）',
    latin: 'Schefflera arboricola',
    file: 'Dwarf_Umbrella_Tree_(Schefflera_arboricola).jpg',
    photo: null,
    tint: '#e8f1e3',
    fact: '傘のように放射状に広がる掌状複葉。寒さにも乾燥にも強く、屋外の玄関先でも育てられるタフさが魅力。',
    near: ['pachira', 'monstera', 'everfresh', 'ficusElastica', 'gajumaru'],
  },
  {
    id: 'dracaena',
    name: 'ドラセナ・マッサンゲアナ（幸福の木）',
    latin: "Dracaena fragrans 'Massangeana'",
    file: "Corn_Plant_(Dracaena_fragrans_'Massangeana').jpg",
    photo: null,
    tint: '#edf1e3',
    fact: '太い幹から放射状に葉を伸ばす。葉の中央に入る黄色い斑が目印で、ハワイでは幸運を呼ぶ木とされます。',
    near: ['chlorophytum', 'sansevieria', 'strelitzia', 'chamaedorea', 'calathea'],
  },
  {
    id: 'zamioculcas',
    name: 'ザミオクルカス（ZZプラント）',
    latin: 'Zamioculcas zamiifolia',
    file: 'ZZ_Plant_(Zamioculcas_zamiifolia)_1.jpg',
    photo: null,
    tint: '#e9efe4',
    fact: '厚く光る小葉が羽状に並ぶ。地下に芋状の塊茎を持ち、暗さ・乾燥・放置にきわめて強い「無敵の観葉植物」。',
    near: ['everfresh', 'sansevieria', 'schefflera', 'chamaedorea', 'aloe'],
  },
  {
    id: 'adiantum',
    name: 'アジアンタム',
    latin: 'Adiantum raddianum',
    file: 'Starr_030807-0143_Adiantum_raddianum.jpg',
    photo: null,
    tint: '#e9f2e6',
    fact: '黒く細い葉柄に、扇形の小葉をふわりと付けるシダ。乾燥に弱く、葉水と高い湿度が管理のポイントです。',
    near: ['everfresh', 'chamaedorea', 'platycerium', 'chlorophytum', 'zamioculcas'],
  },
  {
    id: 'strelitzia',
    name: 'ストレリチア（極楽鳥花）',
    latin: 'Strelitzia reginae',
    file: 'Bird_of_paradise_(Strelitzia_reginae)_02.jpg',
    photo: null,
    tint: '#eaf0e2',
    fact: '長い葉柄の先に厚いパドル状の葉。極楽鳥（ゴクラクチョウ）に似たオレンジ色の花を咲かせることが名前の由来。',
    near: ['dracaena', 'calathea', 'sansevieria', 'chamaedorea', 'monstera'],
  },
  {
    id: 'everfresh',
    name: 'エバーフレッシュ',
    latin: 'Cojoba arborea',
    file: 'Cojoba_arborea_1zz.jpg',
    photo: null,
    tint: '#eaf2e3',
    fact: '夜になると葉を閉じて眠る「就眠運動」をするマメ科の木。羽のように細かい小葉が涼しげです。',
    near: ['adiantum', 'chamaedorea', 'zamioculcas', 'pachira', 'schefflera'],
  },
  {
    id: 'chamaedorea',
    name: 'テーブルヤシ',
    latin: 'Chamaedorea elegans',
    file: 'Chamaedorea_elegans_01.jpg',
    photo: null,
    tint: '#e9f1e4',
    fact: '小型のヤシで、テーブルに置けるサイズが名前の由来。耐陰性が高く、暗めの室内でもよく育ちます。',
    near: ['everfresh', 'adiantum', 'strelitzia', 'dracaena', 'chlorophytum'],
  },
  {
    id: 'calathea',
    name: 'カラテア',
    latin: 'Calathea makoyana',
    file: 'Calathea_makoyana_11zz.jpg',
    photo: null,
    tint: '#ecf0e5',
    fact: '葉の模様が美しく、夜は葉を立てて閉じることから「祈りの植物（プレイヤープラント）」とも呼ばれます。',
    near: ['strelitzia', 'monstera', 'ficusElastica', 'dracaena', 'pothos'],
  },
  {
    id: 'platycerium',
    name: 'ビカクシダ（コウモリラン）',
    latin: 'Platycerium bifurcatum',
    file: 'Platycerium_bifurcatum_kz01.jpg',
    photo: null,
    tint: '#edf0e2',
    fact: '鹿の角のような胞子葉と、株元を覆う貯水葉を持つ着生シダ。木や板に付けて壁掛けで楽しみます。',
    near: ['adiantum', 'monstera', 'strelitzia', 'everfresh', 'chamaedorea'],
  },
  {
    id: 'echinocactus',
    name: 'キンシャチ（金鯱）',
    latin: 'Echinocactus grusonii',
    file: 'Echinocactus_grusonii_001.JPG',
    photo: null,
    tint: '#f1f0de',
    fact: '「サボテンの王様」と呼ばれる球状サボテン。黄金色の鋭いトゲが放射状に並び、大きく育つと直径80cmにも。',
    near: ['aloe', 'sansevieria', 'zamioculcas', 'platycerium', 'calathea'],
  },
];

/* ---------- ファイナル問題（全問正解者のみ） ---------- */

const FINALS = [
  {
    id: 'dioscorea',
    file: 'Dioscorea_elephantipes_001.JPG',
    photo: null,
    tint: '#f2eddd',
    choices: [
      'ディオスコレア・エレファンティペス（亀甲竜）',
      'パキポディウム・グラキリス（象牙宮）',
      'オペルクリカリア・パキプス',
      'アデニウム・オベスム（砂漠のバラ）',
      'ステファニア・エレクタ',
    ],
    answer: 0,
    name: 'ディオスコレア・エレファンティペス（亀甲竜）',
    latin: 'Dioscorea elephantipes',
    fact: '南アフリカ原産のヤマノイモ科の塊根植物。亀の甲羅のように割れる塊根から細いつるを伸ばし、ハート形の葉を付けます。夏に休眠し、秋から冬に生育する「冬型」なのも特徴。',
    hint: '亀の甲羅のように割れた塊根から、細いつるが伸びる。',
  },
  {
    id: 'obesa',
    file: 'Euphorbia_obesa_21.JPG',
    photo: null,
    tint: '#eef0e6',
    choices: [
      'ユーフォルビア・オベサ',
      'アストロフィツム・カブト（兜丸）',
      'ギムノカリキウム・李夫人',
      'ロフォフォラ（烏羽玉）',
      'エキノカクタス・ヘキラン',
    ],
    answer: 0,
    name: 'ユーフォルビア・オベサ',
    latin: 'Euphorbia obesa',
    fact: '南アフリカ原産。サボテンにそっくりですが、トゲが無くトウダイグサ科の多肉植物です。球形と稜（りょう）の縞模様から「野球のボールの植物（baseball plant）」とも呼ばれ、雌雄異株で、雄株と雌株がそろわないと種子ができません。',
    hint: 'トゲの無い球体。サボテンではなくトウダイグサ科。',
  },
  {
    id: 'agave',
    file: 'Agave_titanota_kz1.JPG',
    photo: null,
    tint: '#eff1e4',
    choices: [
      'アガベ・チタノタ',
      'アガベ・アテナータ',
      'アロエ・ディコトマ',
      'ディッキア・マルニエルラポストレイ',
      'ハオルチア・レツーサ',
    ],
    answer: 0,
    name: 'アガベ・チタノタ',
    latin: 'Agave titanota',
    fact: 'メキシコ・オアハカ原産。白みを帯びた肉厚の葉、鋭い鋸歯（きょし）と黒く長い頂棘（ターミナルスパイン）が特徴で、「白鯨」「オテロイ」など多くの選抜個体が流通します。棘の無いアテナータとは対照的な姿。',
    hint: '肉厚の葉に黒く鋭い棘。「白鯨」の名で知られる個体も。',
  },
];
